/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apppersediaanbarang;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//JasperReoprt
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author WILLY PERMANA
 */
public class Menu_Utama extends javax.swing.JFrame {
koneksi kon = new koneksi();
    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
        kon.setKoneksi();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public String KodeUser;
    public String NamaUser;

    public String getKodeUser() {
        return KodeUser;
    }
    public String getNamaUser() {
        return NamaUser;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambarMenu1 = new background.GambarMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lKode = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mgantipass = new javax.swing.JMenuItem();
        mkeluar = new javax.swing.JMenuItem();
        mlogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mkategori = new javax.swing.JMenuItem();
        mproduk = new javax.swing.JMenuItem();
        msupplier = new javax.swing.JMenuItem();
        muser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mbrgmasuk = new javax.swing.JMenuItem();
        mbrgkeluar = new javax.swing.JMenuItem();
        mpo = new javax.swing.JMenuItem();
        mretur = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        mlapkategori = new javax.swing.JMenuItem();
        mlapproduk = new javax.swing.JMenuItem();
        mlapsupplier = new javax.swing.JMenuItem();
        mlapuser = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mlapbrgmasuk = new javax.swing.JMenuItem();
        mlapbrgkeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Menu Utama");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        gambarMenu1.setForeground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        jLabel1.setText("Selamat Datang di Aplikasi Persediaan Barang");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        jLabel2.setText("Hai,");

        lNama.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        lNama.setText("Nama User");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        jLabel4.setText("Kode Anda :");

        lKode.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        lKode.setText("0");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        jLabel6.setText("GADGET STORE");

        javax.swing.GroupLayout gambarMenu1Layout = new javax.swing.GroupLayout(gambarMenu1);
        gambarMenu1.setLayout(gambarMenu1Layout);
        gambarMenu1Layout.setHorizontalGroup(
            gambarMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gambarMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gambarMenu1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNama))
                    .addGroup(gambarMenu1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lKode))
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gambarMenu1Layout.setVerticalGroup(
            gambarMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarMenu1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(gambarMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gambarMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lKode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        mgantipass.setText("Ganti Password");
        mgantipass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgantipassActionPerformed(evt);
            }
        });
        jMenu1.add(mgantipass);

        mkeluar.setText("Keluar");
        mkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkeluarActionPerformed(evt);
            }
        });
        jMenu1.add(mkeluar);

        mlogout.setText("Logout");
        mlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mlogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        mkategori.setText("Kategori");
        mkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkategoriActionPerformed(evt);
            }
        });
        jMenu2.add(mkategori);

        mproduk.setText("Produk");
        mproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprodukActionPerformed(evt);
            }
        });
        jMenu2.add(mproduk);

        msupplier.setText("Supplier");
        msupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msupplierActionPerformed(evt);
            }
        });
        jMenu2.add(msupplier);

        muser.setText("User");
        muser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muserActionPerformed(evt);
            }
        });
        jMenu2.add(muser);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        mbrgmasuk.setText("Barang Masuk");
        mbrgmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrgmasukActionPerformed(evt);
            }
        });
        jMenu3.add(mbrgmasuk);

        mbrgkeluar.setText("Barang Keluar");
        mbrgkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrgkeluarActionPerformed(evt);
            }
        });
        jMenu3.add(mbrgkeluar);

        mpo.setText("Purcase Order");
        mpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpoActionPerformed(evt);
            }
        });
        jMenu3.add(mpo);

        mretur.setText("Retur");
        mretur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mreturActionPerformed(evt);
            }
        });
        jMenu3.add(mretur);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        jMenu5.setText("Data Master");

        mlapkategori.setText("Laporan Kategori");
        mlapkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlapkategoriActionPerformed(evt);
            }
        });
        jMenu5.add(mlapkategori);

        mlapproduk.setText("Laporan Produk");
        mlapproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlapprodukActionPerformed(evt);
            }
        });
        jMenu5.add(mlapproduk);

        mlapsupplier.setText("Laporan Supplier");
        mlapsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlapsupplierActionPerformed(evt);
            }
        });
        jMenu5.add(mlapsupplier);

        mlapuser.setText("Laporan User");
        mlapuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlapuserActionPerformed(evt);
            }
        });
        jMenu5.add(mlapuser);

        jMenu4.add(jMenu5);

        jMenu6.setText("Data Transaksi");

        mlapbrgmasuk.setText("Laporan Barang Masuk");
        mlapbrgmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlapbrgmasukActionPerformed(evt);
            }
        });
        jMenu6.add(mlapbrgmasuk);

        mlapbrgkeluar.setText("Laporan Barang Keluar");
        mlapbrgkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlapbrgkeluarActionPerformed(evt);
            }
        });
        jMenu6.add(mlapbrgkeluar);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lKode.setText(KodeUser);
        lNama.setText(NamaUser);
    }//GEN-LAST:event_formWindowActivated

    private void mkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkeluarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar",
                "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else{
            
        }
    }//GEN-LAST:event_mkeluarActionPerformed

    private void mlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        App_Login l = new App_Login();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
    }//GEN-LAST:event_mlogoutActionPerformed

    private void mgantipassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgantipassActionPerformed
        // TODO add your handling code here:
        dispose();
        App_Ganti_Password gp = new App_Ganti_Password();
        gp.setLocationRelativeTo(null);
        gp.setVisible(true);
        gp.KodeUser=lKode.getText();
    }//GEN-LAST:event_mgantipassActionPerformed

    private void mkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkategoriActionPerformed
        // TODO add your handling code here:
        Master_Kategori k = new Master_Kategori();
        k.setLocationRelativeTo(null);
        k.setVisible(true);
    }//GEN-LAST:event_mkategoriActionPerformed

    private void mprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprodukActionPerformed
        // TODO add your handling code here:
        Master_Produk p = new Master_Produk();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_mprodukActionPerformed

    private void msupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msupplierActionPerformed
        // TODO add your handling code here:
        Master_Supplier s = new Master_Supplier();
        s.setLocationRelativeTo(null);
        s.setVisible(true);
    }//GEN-LAST:event_msupplierActionPerformed

    private void muserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muserActionPerformed
        // TODO add your handling code here:
        Master_User u = new Master_User();
        u.setLocationRelativeTo(null);
        u.setVisible(true);
    }//GEN-LAST:event_muserActionPerformed

    private void mbrgmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrgmasukActionPerformed
        // TODO add your handling code here:
        Transaksi_BarangMasuk bm = new Transaksi_BarangMasuk();
        bm.setLocationRelativeTo(null);
        bm.setVisible(true);
        bm.KodeUser=lKode.getText();
    }//GEN-LAST:event_mbrgmasukActionPerformed

    private void mbrgkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrgkeluarActionPerformed
        // TODO add your handling code here:
        Transaksi_BarangKeluar bk = new Transaksi_BarangKeluar();
        bk.setLocationRelativeTo(null);
        bk.setVisible(true);
        bk.KodeUser=lKode.getText();
    }//GEN-LAST:event_mbrgkeluarActionPerformed

    private void mlapprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlapprodukActionPerformed
        // TODO add your handling code here:
        try{
            String path="src/apppersediaanbarang/Laporan_Produk.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mlapprodukActionPerformed

    private void mlapkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlapkategoriActionPerformed
        // TODO add your handling code here:
        try{
            String path="src/apppersediaanbarang/Laporan_Kategori.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mlapkategoriActionPerformed

    private void mlapuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlapuserActionPerformed
        // TODO add your handling code here:
        try{
            String path="src/apppersediaanbarang/Laporan_User.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mlapuserActionPerformed

    private void mlapsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlapsupplierActionPerformed
        // TODO add your handling code here:
        try{
            String path="src/apppersediaanbarang/Laporan_Supplier.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mlapsupplierActionPerformed

    private void mlapbrgmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlapbrgmasukActionPerformed
        // TODO add your handling code here:
        Laporan_TransaksiMasuk ltm = new Laporan_TransaksiMasuk();
        ltm.setLocationRelativeTo(null);
        ltm.setVisible(true);
    }//GEN-LAST:event_mlapbrgmasukActionPerformed

    private void mlapbrgkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlapbrgkeluarActionPerformed
        // TODO add your handling code here:
        Laporan_TransaksiKeluar ltk = new Laporan_TransaksiKeluar();
        ltk.setLocationRelativeTo(null);
        ltk.setVisible(true);
    }//GEN-LAST:event_mlapbrgkeluarActionPerformed

    private void mpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpoActionPerformed
        // TODO add your handling code here:
        Transaksi_PurcaseOrder po = new Transaksi_PurcaseOrder();
        po.setLocationRelativeTo(null);
        po.setVisible(true);
        po.KodeUser=lKode.getText();
    }//GEN-LAST:event_mpoActionPerformed

    private void mreturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mreturActionPerformed
        // TODO add your handling code here:
        Transaksi_ReturBarang rb = new Transaksi_ReturBarang();
        rb.setLocationRelativeTo(null);
        rb.setVisible(true);
        rb.KodeUser=lKode.getText();
    }//GEN-LAST:event_mreturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private background.GambarMenu gambarMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lKode;
    private javax.swing.JLabel lNama;
    private javax.swing.JMenuItem mbrgkeluar;
    private javax.swing.JMenuItem mbrgmasuk;
    private javax.swing.JMenuItem mgantipass;
    private javax.swing.JMenuItem mkategori;
    private javax.swing.JMenuItem mkeluar;
    private javax.swing.JMenuItem mlapbrgkeluar;
    private javax.swing.JMenuItem mlapbrgmasuk;
    private javax.swing.JMenuItem mlapkategori;
    private javax.swing.JMenuItem mlapproduk;
    private javax.swing.JMenuItem mlapsupplier;
    private javax.swing.JMenuItem mlapuser;
    private javax.swing.JMenuItem mlogout;
    private javax.swing.JMenuItem mpo;
    private javax.swing.JMenuItem mproduk;
    private javax.swing.JMenuItem mretur;
    private javax.swing.JMenuItem msupplier;
    private javax.swing.JMenuItem muser;
    // End of variables declaration//GEN-END:variables
}
